<option value="ARABIC_LANGUAGE_TRAINING_WITH_THESIS">ARABIC LANGUAGE TRAINING (WİTHTHESİS)</option>
<option value="ARABIC_LANGUAGE_TRAINING_WITHOUT_THESIS">ARABIC LANGUAGE TRAINING (WİTHOUTTHESİS)</option>
<option value="BANKING_AND_INSURANCE_WITH_THESIS">BANKING AND INSURANCE (WİTHTHESİS)</option>
<option value="BANKING_AND_INSURANCE_WITHOUT_THESIS">BANKING AND INSURANCE (WİTHOUTTHESİS)</option>
<option value="BANKING_AND_FINANCE_DE">BANKING AND FINANCE (DE)</option>
<option value="INTERNATIONAL_ECONOMY_WITH_THESIS">INTERNATIONAL ECONOMY (WİTHTHESİS)</option>
<option value="INTERNATIONAL_ECONOMY_WITHOUT_THESIS">INTERNATIONAL ECONOMY (WİTHOUTTHESİS)</option>
<option value="NEW_MEDIA_WITH_THESIS">NEW MEDIA (WİTHTHESİS)</option>
<option value="NEW_MEDIA_WITHOUT_THESIS">NEW MEDIA (WİTHOUTTHESİS)</option>
<option value="INFORMATION_TECHNOLOGY_LAW_WITH_THESIS">INFORMATION TECHNOLOGY LAW (WİTHTHESİS)</option>
<option value="E_BUSINESS_MANAGEMENT_DE_WITHOUT_THESIS">E - BUSINESS MANAGEMENT (DISTANCE EDUCATION )(WİTHOUTTHESİS)
</option>
<option value="HUMAN_RESOURCE_MANAGEMENT_WITH_THESIS">HUMAN RESOURCE MANAGEMENT (WİTHTHESİS)</option>
<option value="HUMAN_RESOURCE_MANAGEMENT_WITHOUT_THESIS">HUMAN RESOURCE MANAGEMENT (WİTHOUTTHESİS)</option>
<option value="BUSINESS_ADMINISTRATION_WITH_THESIS">BUSINESS ADMINISTRATION (WİTHTHESİS)</option>
<option value="STRATEGIC_MARKETING_AND_BRAND_MANAGEMENT_WITHOUT_THESIS">STRATEGIC MARKETING AND BRAND MANAGEMENT
    (WİTHOUTTHESİS)</option>
<option value="DIGITAL_MARKETING_DE_WITHOUT_THESIS">DIGITAL MARKETING (WİTHOUTTHESİS)(DE)</option>
<option value="BUSINESS_MANAGEMENT_FOR_BUSINESS_MANAGER_WITHOUT_THESIS">BUSINESS MANAGEMENT FOR BUSINESS MANAGER
    (WİTHOUTTHESİS)</option>
<option value="QUALITY_MANAGEMENT_AND_QUALITY_ASSURANCE_SYSTEMS_WITH_THESIS">QUALITY MANAGEMENT AND QUALITY ASSURANCE
    SYSTEMS (WİTHTHESİS)</option>
<option value="QUALITY_MANAGEMENT_AND_QUALITY_ASSURANCE_SYSTEMS_WITHOUT_THESIS">QUALITY MANAGEMENT AND QUALITY ASSURANCE
    SYSTEMS (WİTHOUTTHESİS)</option>
<option value="EDUCATION_MANAGEMENT_WITH_THESIS">EDUCATION MANAGEMENT(WİTHTHESİS)</option>
<option value="EDUCATION_MANAGEMENT_WITHOUT_THESIS">EDUCATION MANAGEMENT(WİTHOUT THESİS)</option>
<option value="VISUAL_ARTS_WITH_THESIS">VISUAL ARTS (WİTHTHESİS)</option>
<option value="GRAPHIC_DESIGN_WITH_THESIS">GRAPHIC DESIGN (WİTHTHESİS)</option>
<option value="JOURNALISM_WITH_THESIS">JOURNALISM (WİTHTHESİS)</option>
<option value="JOURNALISM_WITHOUT_THESIS">JOURNALISM (WİTHOUTTHESİS)</option>
<option value="PUBLIC_RELATIONS_AND_PUBLICITY_WITH_THESIS">PUBLIC RELATIONS AND PUBLICITY (WİTHTHESİS)</option>
<option value="PUBLIC_RELATIONS_AND_PUBLICITY_WITHOUT_THESIS">PUBLIC RELATIONS AND PUBLICITY (WİTHOUTTHESİS)</option>
<option value="ELEMENTARY_EDUCATION_WITH_THESIS">ELEMENTARY EDUCATION (WİTHTHESİS)</option>
<option value="ELEMENTARY_EDUCATION_WITHOUT_THESIS">ELEMENTARY EDUCATION (WİTHOUTTHESİS)</option>
<option value="ENGLISH_LANGUAGE_TEACHING_WITH_THESIS">ENGLISH LANGUAGE TEACHING (WİTHTHESİS)</option>
<option value="ENGLISH_LANGUAGE_TEACHING_WITHOUT_THESIS">ENGLISH LANGUAGE TEACHING (WİTHOUTTHESİS)</option>
<option value="ENGLISH_LANGUAGE_AND_LITERATURE_WITH_THESIS">ENGLISH LANGUAGE AND LITERATURE (WİTHTHESİS)</option>
<option value="BUSINESS_MANAGEMENT_DE_IN_ENGLISH_WITHOUT_THESIS">BUSINESS MANAGEMENT(DE)(IN ENGLISH)(WİTHOUTTHESİS)
</option>
<option value="BUSINESS_ADMINISTRATION_IN_ENGLISH_WITH_THESIS">BUSINESS ADMINISTRATION (IN ENGLISH)(WİTHTHESİS)</option>
<option value="BUSINESS_MANAGEMENT_FOR_BUSINESS_MANAGER_IN_ENGLISH_WITHOUT_THESIS">BUSINESS MANAGEMENT FOR BUSINESS
    MANAGER (IN ENGLISH)(WİTHOUTTHESİS)</option>
<option value="PUBLIC_LAW_WITH_THESIS">PUBLIC LAW(WİTHTHESİS)</option>
<option value="PUBLIC_LAW_WITHOUT_THESIS">PUBLIC LAW (WİTHOUTTHESİS)</option>
<option value="CLINICAL_PSYCHOLOGY_WITH_THESIS">CLINICAL PSYCHOLOGY (WİTHTHESİS)</option>
<option value="CLINICAL_PSYCHOLOGY_WITHOUT_THESIS">CLINICAL PSYCHOLOGY (WİTHOUTTHESİS)</option>
<option value="PSYCHOLOGY_WITH_THESIS">PSYCHOLOGY (WİTHTHESİS)</option>
<option value="PSYCHOLOGY_WITHOUT_THESIS">PSYCHOLOGY (WİTHOUTTHESİS)</option>
<option value="PSYCHOLOGICAL_COUNSELING_AND_GUIDANCE_WITH_THESIS">PSYCHOLOGİCAL COUNSELİNG AND GUİDANCE (WİTH THESİS)
</option>
<option value="PSYCHOLOGICAL_COUNSELING_AND_GUIDANCE_WITHOUT_THESIS">PSYCHOLOGİCAL COUNSELİNG AND GUİDANCE (WİTHOUT
    THESİS)</option>
<option value="LOCAL_GOVERNMENTS_AND_DECENTRALIZATION_WITH_THESIS">LOCAL GOVERMENTS AND DECENTRALIZATION (WİTHTHESİS)
</option>
<option value="LOCAL_GOVERNMENTS_AND_DECENTRALIZATION_WITHOUT_THESIS">LOCAL GOVERMENTS AND DECENTRALIZATION
    (WİTHOUTTHESİS)</option>
<option value="LOCAL_GOVERNMENTS_AND_DECENTRALIZATION_DE_WITHOUT_THESIS">LOCAL GOVERMENTS AND DECENTRALIZATION
    (WİTHOUTTHESİS)(DE)</option>
<option value="ACCOUNTING_AND_AUDITING_WITH_THESIS">ACCOUNTING AND AUDITING (WİTHTHESİS)</option>
<option value="ACCOUNTING_AND_AUDITING_WITHOUT_THESIS">ACCOUNTING AND AUDITING (WİTHOUTTHESİS)</option>
<option value="ACCOUNTING_AND_AUDITING_IN_ENGLISH_WITH_THESIS">ACCOUNTING AND AUDITING (IN ENGLİSH) (WİTHTHESİS)
</option>
<option value="ACCOUNTING_AND_AUDITING_IN_ENGLISH_WITHOUT_THESIS">ACCOUNTING AND AUDITING (IN ENGLİSH) (WİTHOUTTHESİS)
</option>
<option value="TRANSLATION_AND_INTERPRETING_TURKISH_RUSSIAN_WITH_THESIS">TRANSLATION AND INTERPRETING (TURKISH -
    RUSSIAN) (WİTHTHESİS)</option>
<option value="PRE_SCHOOL_EDUCATION_WITH_THESIS">PRE-SCHOOL EDUCATION (WİTHTHESİS)</option>
<option value="PRE_SCHOOL_EDUCATION_WITHOUT_THESIS">PRE-SCHOOL EDUCATION (WİTHOUTTHESİS)</option>
<option value="PRIVATE_LAW_WITH_THESIS">PRIVATE LAW (WİTHTHESİS)</option>
<option value="PRIVATE_LAW_WITHOUT_THESIS">PRIVATE LAW (WİTHOUTTHESİS)</option>
<option value="PERFORMING_ARTS_WITH_THESIS">PERFORMING ARTS (WİTHTHESIS)</option>
<option value="POLITICAL_SCIENCE_AND_INTERNATIONAL_RELATIONS_IN_ENGLISH_WITH_THESIS">POLITICAL SCIENCE AND INTERNATIONAL
    RELATIONS (IN ENGLISH)(WİTHTHESİS)</option>
<option value="POLITICAL_SCIENCE_AND_INTERNATIONAL_RELATIONS_IN_ENGLISH_WITHOUT_THESIS">POLITICAL SCIENCE AND
    INTERNATIONAL RELATIONS (IN ENGLISH)(WİTHOUTTHESİS)</option>
<option value="INTERNATIONAL_RELATIONS_AND_INTELLIGENCE_STUDIES_WITH_THESIS">INTERNATIONAL RELATIONS AND INTELLIGENCE
    STUDIES (WİTHTHESİS)</option>
<option value="INTERNATIONAL_RELATIONS_AND_TERRORISM_RESEARCHS_WITH_THESIS">INTERNATIONAL RELATIONS AND TERRORISM
    RESEARCHS (WİTHTHESİS)</option>
<option value="SOCIOLOGY_WITH_THESIS">SOCIOLOGY (WİTHTHESİS)</option>
<option value="HISTORY_WITH_THESIS">HISTORY (WİTHTHESİS)</option>
<option value="TELEVISION_AND_FILM_WITH_THESIS">TELEVISION AND FILM (WİTHTHESİS)</option>
<option value="TELEVISION_AND_FILM_WITHOUT_THESIS">TELEVISION AND FILM (WİTHOUTTHESİS)</option>
<option value="TURKISH_LANGUAGE_AND_LITERATURE_WITH_THESIS">TURKISH LANGUAGE AND LITERATURE (WİTHTHESİS)</option>
<option value="TURKISH_EDUCATION_MA_WITH_THESIS">TURKISH EDUCATION (MA)(WİTHTHESİS)</option>
<option value="COMPUTER_ENGINEERING_WITH_THESIS">COMPUTER ENGINEERING (WİTHTHESİS)</option>
<option value="COMPUTER_ENGINEERING_IN_ENGLISH_WITH_THESIS">COMPUTER ENGINEERING (IN ENGLİSH) (WİTHTHESİS)</option>
<option value="COMPUTER_ENGINEERING_IN_ENGLISH_WITHOUT_THESIS">COMPUTER ENGINEERING (IN ENGLİSH) (WİTHOUT THESİS)
</option>
<option value="INFORMATION_TECHNOLOGY_WITHOUT_THESIS">INFORMATION TECHNOLOGY (WİTHOUTTHESİS)</option>
<option value="IT_BASED_TEACHING_TECHNOLOGIES_WITHOUT_THESIS">IT BASED TEACHING TECHNOLOGIES (WİTHOUTTHESİS)</option>
<option value="ELECTRICAL_AND_ELECTRONIC_ENGINEERING_WITH_THESIS">ELECTRICAL AND ELECTRONIC ENGINEERING (WİTHTHESİS)
</option>
<option value="ELECTRICAL_AND_ELECTRONIC_ENGINEERING_IN_ENGLISH_WITH_THESIS">ELECTRICAL AND ELECTRONIC ENGINEERING (IN
    ENGLISH)(WİTHTHESİS)</option>
<option value="ELECTRICAL_AND_ELECTRONIC_ENGINEERING_IN_ENGLISH_WITHOUT_THESIS">ELECTRICAL AND ELECTRONIC ENGINEERING
    (IN ENGLISH)(WİTHOUT THESİS)</option>
<option value="ENERGY_TECHNOLOGIES_IN_ENGLISH_WITH_THESIS">ENERGY TECHNOLOGIES (IN ENGLİSH)(WİTH THESİS)</option>
<option value="ENERGY_TECHNOLOGIES_IN_ENGLISH_WITHOUT_THESIS">ENERGY TECHNOLOGIES (IN ENGLİSH)(WİTHOUT THESİS)</option>
<option value="FOOD_SAFETY_WITH_THESIS">FOOD SAFETY (WİTHTHESİS)</option>
<option value="FOOD_ENGINEERING_WITH_THESIS">FOOD ENGINEERING (WİTHTHESİS)</option>
<option value="CIVIL_ENGINEERING_WITH_THESIS">CIVIL ENGINEERING (WİTHTHESİS)</option>
<option value="EARTHQUAKE_AND_STRUCTURAL_ENGINEERING_WITH_THESIS">EARTHQUAKE AND STRUCTURAL ENGİNEERİNG (WİTH THESİS)
</option>
<option value="EARTHQUAKE_AND_STRUCTURAL_ENGINEERING_WITHOUT_THESIS">EARTHQUAKE AND STRUCTURAL ENGİNEERİNG (WİTHOUT
    THESİS)</option>
<option value="INDUSTRIAL_ENGINEERING_IN_ENGLISH_WITH_THESIS">INDUSTRİAL ENGİNEERİNG (IN ENGLİSH) (WİTH THESİS)</option>
<option value="INDUSTRIAL_ENGINEERING_IN_ENGLISH_WITHOUT_THESIS">INDUSTRİAL ENGİNEERİNG (IN ENGLİSH) (WİTHOUT THESİS)
</option>
<option value="CIVIL_ENGINEERING_CONSTRUCTION_AND_PROJECT_MANAGEMENT_WITHOUT_THESIS">CIVIL ENGINEERING CONSTRUCTION AND
    PROJECT MANAGEMENT (WİTHOUTTHESİS)</option>
<option value="OCCUPATIONAL_HEALTH_AND_SAFETY_WITH_THESIS">OCCUPATIONAL HEALTH AND SAFETY (WİTHTHESİS)</option>
<option value="OCCUPATIONAL_HEALTH_AND_SAFETY_WITHOUT_THESIS">OCCUPATIONAL HEALTH AND SAFETY (WİTHOUTTHESİS)</option>
<option value="URBAN_DESIGN_WITHOUT_THESIS">URBAN DESIGN (WİTHOUTTHESİS)</option>
<option value="ARCHITECTURAL_DESIGN_WITH_THESIS">ARCHITECTURAL DESIGN (WİTHTHESİS)</option>
<option value="ARCHITECTURAL_DESIGN_WITHOUT_THESIS">ARCHITECTURAL DESIGN (WİTHOUTTHESİS)</option>
<option value="ARCHITECTURE_WITH_THESIS">ARCHITECTURE (WİTHTHESİS)</option>
<option value="ARCHITECTURE_WITHOUT_THESIS">ARCHITECTURE (WİTHOUT THESİS)</option>
<option value="URBAN_RENEWAL_WITH_THESIS">URBAN RENEWAL (WİTHTHESİS)</option>
<option value="MECHANICAL_ENGINEERING_WITH_THESIS_IN_ENGLISH">MECHANICAL ENGINEERING (WİTHTHESİS)(IN ENGLISH)</option>
<option value="MECHANICAL_ENGINEERING_WITH_THESIS">MECHANICAL ENGINEERING (WİTHTHESİS)</option>
<option value="MECHATRONICS_ENGINEERING_WITH_THESIS">MECHATRONICS ENGINEERING (WİTHTHESİS)</option>
<option value="ARTIFICIAL_INTELLIGENCE_AND_DATA_SCIENCE_ENGLISH_WITH_THESIS">ARTIFICIAL INTELLIGENCE AND DATA SCIENCE
    (ENGLİSH) (WİTHTHESİS)</option>
<option value="MOUTH_TEETH_AND_JAW_SURGERY_WITH_THESIS">MOUTH, TEETH AND JAW SURGERY (WİTHTHESİS)</option>
<option value="ORTHODONTICS_WITH_THESIS">ORTHODONTICS (WİTHTHESİS)</option>
<option value="ORTHODONTICS_WITHOUT_THESIS">ORTHODONTICS (WİTHOUTTHESİS)</option>
<option value="PERIODONTOLOGY_WITH_THESIS">PERIODONTOLOGY (WİTHTHESİS)</option>
<option value="PROTECTIVE_TOOTH_TREATMENT_WITH_THESIS">PROTECTIVE TOOTH TREATMENT (WİTHTHESİS)</option>
<option value="PROTECTIVE_TOOTH_TREATMENT_WITHOUT_THESIS">PROTECTIVE TOOTH TREATMENT (WİTHOUTTHESİS)</option>
<option value="MOLECULAR_MEDICINE_WITH_THESIS">MOLECULAR MEDICINE (WİTHTHESİS)</option>
<option value="NUTRITION_AND_DIETETICS_WITH_THESIS">NUTRITION AND DIETETICS (WİTHTHESİS)</option>
<option value="AUDIOLOGY_WITH_THESIS">AUDIOLOGY (WİTHTHESİS)</option>
<option value="SOCIAL_SERVICE_WITH_THESIS">SOCIAL SERVICE (WİTHTHESİS)</option>
<option value="SOCIAL_SERVICE_WITHOUT_THESIS">SOCIAL SERVICE (WİTHOUTTHESİS)</option>
<option value="MEDICAL_MICROBIOLOGY_WITH_THESIS">MEDICAL MICROBIOLOGY (WİTHTHESİS)</option>
<option value="MEDICAL_MICROBIOLOGY_WITHOUT_THESIS">MEDICAL MICROBIOLOGY (WİTHOUTTHESİS)</option>
<option value="FAMILY_COUNSELING_WITH_THESIS">FAMILY COUNSELING (WİTHTHESİS)</option>
<option value="FAMILY_COUNSELING_WITHOUT_THESIS">FAMILY COUNSELING (WİTHOUTTHESİS)</option>
<option value="PHYSICAL_EDUCATION_AND_SPORTS_WITH_THESIS">PHYSICAL EDUCATION AND SPORTS (WİTHTHESİS)</option>
<option value="PHYSIOTHERAPY_AND_REHABILITATION_WITH_THESIS">PHYSIOTHERAPY AND REHABILITATION (WİTHTHESİS)</option>
<option value="PHYSIOTHERAPY_AND_REHABILITATION_WITHOUT_THESIS">PHYSIOTHERAPY AND REHABILITATION (WİTHOUT THESİS)
</option>
<option value="HEALTH_PHYSICS_WITH_THESIS">HEALTH PHYSICS (WİTHTHESİS)</option>
<option value="HEALTH_MANAGEMENT_WITH_THESIS">HEALTH MANAGEMENT (WİTHTHESİS)</option>
<option value="HEALTH_MANAGEMENT_WITHOUT_THESIS">HEALTH MANAGEMENT (WİTHOUTTHESİS)</option>
<option value="MEDICAL_PHARMACOLOGY_WITH_THESIS">MEDICAL PHARMACOLOGY (WİTHTHESİS)</option>
<option value="MEDICAL_PHARMACOLOGY_WITHOUT_THESIS">MEDICAL PHARMACOLOGY (WİTHOUTTHESİS)</option>